DEFAULT_POINT_END_TOKEN = "<point_end>"
DEFAULT_POINT_PATCH_TOKEN = "<point_patch>"
DEFAULT_POINT_START_TOKEN = "<point_start>"
DEATULT_POINT_TOKEN = "<point>"
POINT_TOKEN_INDEX = -200
IGNORE_INDEX = -100