model : {
  NAME: PointTransformer,
  trans_dim: 1152, # * point feature dims (hidden state)
  depth: 12, 
  drop_path_rate: 0.1, 
  cls_dim: 40, 
  num_heads: 12,
  group_size: 48, 
  num_group: 512,
  encoder_dims: 512, # * point group tokens feature
  point_input_dims: 6,
  # resume: "exp-1/model_40000.pth",
  # save_dir: "exp-2",
}
train: {
  base_lr: 0.001,
  total_step: 48000,
  eval_freq: 2000,
  save_freq: 2000,
  log_freq: 100,
}
data : {
  batch_size: 32,
  eval_batch_size: 100,
  workers: 4,
  data_root: "/data2/llf/partnet",
  npoints: 8192,
}